config wifi-device 'radio0'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi'
	option band '5g'
	option channel '157'
	option htmode 'HE80'
	option country 'US'
	option mu_beamformer '1'
	option cell_density '3'

config wifi-iface 'default_radio0'
	option device 'radio0'
	option network 'wifi'
	option mode 'ap'
	option ssid 'openwrt_5G'
	option encryption 'psk2'
	option key '0123456789'

config wifi-device 'radio1'
	option type 'mac80211'
	option path 'platform/soc@0/c000000.wifi+1'
	option band '2g'
	option channel '6'
	option htmode 'HT40'
	option country 'US'
	option mu_beamformer '1'
	option cell_density '3'
	option noscan '1'
	option vendor_vht '1'

config wifi-iface 'default_radio1'
	option device 'radio1'
	option network 'lan wifi'
	option mode 'ap'
	option ssid 'openwrt_2.4G'
	option encryption 'psk2'
	option key '0123456789'

config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option packet_steering '1'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'lan1'
	list ports 'lan2'
	list ports 'lan3'
	option promisc '1'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '192.168.50.1'
	option netmask '255.255.255.0'
	option ip6assign '60'
	option delegate '0'

config interface 'wan6'
	option device 'wan'
	option proto 'dhcpv6'

config interface 'wan'
	option proto 'pppoe'
	option device 'wan'
	option username '1897979776201'
	option password '525131'

config interface 'wifi'
	option proto 'dhcp'
	option device 'phy1-ap0'
	option type 'bridge'

