name: Compress Kernel and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache UPX
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/upx
          key: ${{ runner.os }}-upx-${{ hashFiles('**/upx') }}

      - name: Install UPX
        run: |
          if ! command -v upx &> /dev/null; then
            echo "UPX not found, installing..."
            sudo apt-get install upx-ucl -y
          else
            echo "UPX already installed."
          fi

      - name: Download kernel file
        run: |
          KERNEL_URL="https://github.com/MetaCubeX/mihomo/releases/download/v1.18.9/mihomo-linux-armv5-v1.18.9.gz"
          wget $KERNEL_URL -O mihomo-linux-armv5-v1.18.9.gz

      - name: Check downloaded kernel file
        run: ls -l

      - name: Decompress kernel file
        run: gunzip -f mihomo-linux-armv5-v1.18.9.gz

      - name: Set executable permission
        run: chmod +x mihomo-linux-armv5-v1.18.9  # 设置可执行权限

      - name: Compress kernel file
        run: |
          upx --lzma --brute mihomo-linux-armv5-v1.18.9
          mv mihomo-linux-armv5-v1.18.9 clash  # 将文件重命名为 clash
          ls -l # 检查是否生成了压缩后的文件

      - name: Upload compressed kernel file
        uses: actions/upload-artifact@v3  # 确保使用最新版本
        with:
          name: compressed-kernel
          path: clash  # 上传重命名后的文件
